Task 002/logger
GRPilot/sfml-game-engine pull request #2
Opened 2020-12-15 20:03 UTC by GRPilot

2020-12-16 05:07 UTC, GRPilot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add logger (002)](https://trello.com/c/WjkDJpzm/10-add-logger-002)

2020-12-16 20:30 UTC, imblowfish requested changes

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +std::string lvl2str(LogLevels level) {
lvl2str, мы ж тут не linux разрабатываем, давайте не будем писать как наркоманский винни-пух

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +namespace {
Этот namespace навевает желание разместить их в сокрытых методах класса логгера

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +    log("");
шо это за пимпочка

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +    // }
и эта помпушечка

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +    Logger::lastLevel = level;
прикольно, но сомневаюсь, что кто-то реально будет один раз назначать уровень логирования и дальше кайфовать при разрастании проекта
представь, функция, которая вызывает другую, в ней вызывается третья, и там еще какая, и в каждой из них ставится свой уровень логирования, проект большой, собирается долго
я б лишний раз перекрестился и не поленился опять поставить уровень логирования

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +void Logger::logv(LogLevels level, const std::string &format, va_list params) {
требуется капитан, чтобы объяснить, чем отличается действие вот этого logv от log, если я вижу только заголовочник с объявлением рядом
log(LogLevels level, ....)
logv(LogLevels level, ...)

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.cpp
> +    offset += snprintf(offset, end - offset, "%s", CRLF);
вот тут слишком много написано для такой простой вещи, как мне кажется

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.hpp
> +    friend class core::singleton<Logger>;
предпочитаю смотреть на классы как связанные сущности, а не по тому, как в данный момент удобнее сэкономить на коде
лучше не делать Logger наследником singletone, да и вообще избавиться от класса singletone, в нем всего одна функция, которую можно спокойно описывать в каждом классе.
можно еще проще, скрыть класс логгера в namespace, там же экземпляр singletone<Logger> sLogger
сделать открытую функцию getLogger(), и возвращать sLogger.getIntance()

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.hpp
> +    Logger();
Logger = delete;

2020-12-16 20:30 UTC, imblowfish commented on logger/logger.hpp
> +                   const std::vector<printer_t> &printers = getDefaultPrinters(LOG_ALL));
хз на счет вызова функции в параметре по умолчанию
плюс, много где используется std::vector<printer_t>, using Printers = std::vector<printer_t>

2020-12-16 20:30 UTC, imblowfish commented on platform/platform.hpp
> +#include <stdio.h>
cstdio

2020-12-16 20:35 UTC, imblowfish requested changes
В общем по всему пулу, мне кажется, что реализация таких низкоуровневых вещей, как логгер на данном этапе проекта не является решающей, поэтому можно и мержить.
Но лучше начинать разработку с более абстрактных и высокоуровневых вещей, вроде решения, какие подсистемы будут в движке, вроде системы рендеринга, работы с музыкой, анимацией и т.д., далее реализовывать их интерфейсы.
После этого организовывать их взаимодействие между собой, также абстрактно, не вдаваясь в детали реализации. И уже после этого наполнять описанные интерфейсы кодом, которые реально что-то делает.
Так, можно будет сохранять красивую архитектуру

2020-12-17 05:11 UTC, GRPilot commented on engine/inc/core.hpp
> +sf::Color toSfColor(const T *array, size_t size) try {
Ну вообще это все таки ради std::out_of_range
Не знаю, мне кажется это логичным. С другой стороны не думаю, что будет хоть один кейс с передачей указателя не на массив

2020-12-17 05:32 UTC, GRPilot commented on engine/inc/core.hpp
> +sf::Color toSfColor(const T *array, size_t size) try {
Переписал, теперь не нужна обертка

2020-12-17 05:32 UTC, GRPilot commented on engine/inc/core.hpp
> +struct singleton {
Да, ты прав. Думал об этом, но забыл

2020-12-17 05:38 UTC, GRPilot commented on logger/logger.hpp
> +    Logger();
не, нам нужно инициализировать в друге getLogger

2020-12-17 05:54 UTC, GRPilot commented on logger/logger.cpp
> +    offset += snprintf(offset, end - offset, "%s", CRLF);
Почему? Вроде все конкретно. А как сделать проще?

2020-12-17 05:58 UTC, GRPilot commented
> В общем по всему пулу, мне кажется, что реализация таких низкоуровневых вещей, как логгер на данном этапе проекта не является решающей, поэтому можно и мержить.
> Но лучше начинать разработку с более абстрактных и высокоуровневых вещей, вроде решения, какие подсистемы будут в движке, вроде системы рендеринга, работы с музыкой, анимацией и т.д., далее реализовывать их интерфейсы.
> После этого организовывать их взаимодействие между собой, также абстрактно, не вдаваясь в детали реализации. И уже после этого наполнять описанные интерфейсы кодом, которые реально что-то делает.
> Так, можно будет сохранять красивую архитектуру

Я с тобой полностью согласен. Но логгер надо бы доделать все равно. 
Он не является решающей, и его я хотел добавить только ради эксперементов с ImGui и  SFML. Чисто как песочница.
Потом все равно надо его апгрейдить. Но и сейчас он не помешает

2020-12-17 19:06 UTC, imblowfish commented on logger/logger.cpp
> +    offset += snprintf(offset, end - offset, "%s", CRLF);
так, ну во первых есть chrono и put_time, далее CRLF не стоят того, чтобы для них вызывать snprintf, это всего 2 экранированных символа.
еще vsnprintf можно переводить в буфер чуть выше, как по мне, чтобы читалось следующим образом
какой-нибудь stringstream s << put_time(&localtime(&time), "[%F %T] ") << lvl2str(level) << params(наш уже записанный в string) << "\r\n";

2020-12-18 04:51 UTC, GRPilot commented on engine/src/engmain.cpp
> +            bgColor = core::toSfColor(color);
Да это ж демка, лол

2020-12-18 04:51 UTC, GRPilot commented on engine/src/engmain.cpp
> +        ImGui::InputText("Window title", windowTitle, sizeof(windowTitle));
Демка, этого всего не будет после создания архитектуры

2020-12-21 07:16 UTC, merged